version: '3'
services:
  python3:
    restart: always
    build: ./sample_app
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./sample_app:/root/sample_app

  uwsgi:
    # ビルドするDockerfileのでディレクトリ相対パス
    build: ./sample_app
    # 指定したパスをコンテナにマウントする。"ホストのパス:コンテナのパス"となる
    volumes:
      - ./sample_app:/var/www/
    # 解放するポートを指定。"ホスト:コンテナ"のマッピング となる
    ports:
      - "3031:3031"
    # コンテナ内の環境変数を指定する
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # nginxのログをホストOSの /tmp/nginx_log に出力する
      - /tmp/nginx_log:/var/log/nginx
    links:
      - uwsgi
    ports:
      - "4231:80"
    environment:
      TZ: "Asia/Tokyo"
